Audit and Fixed text-files.md
Seneca-ICTOER/IPC144 pull request #140
Opened 2021-12-02 21:03 UTC by joshuali7536

Fixes #122

- Fixed typos and grammar
- Checked Desktop, Mobile, Light & Dark
- Checked Lighthouse and Web Hint
- Added better alt tags for images
- Changed blockquotes to use Admonitions
- Added inter-site links
- Added Frontmatter

2021-12-03 22:47 UTC, Kevan-Y commented
@joshuali7536 Hi, there is a recent change where we remove `slug` (#142).  Could you kindly remove slug in all you changed files, thank you

2021-12-08 15:07 UTC, joshuali7536 commented
@Kevan-Y the `slug` has been removed from the modified files.

2021-12-08 15:27 UTC, Kevan-Y requested changes

2021-12-08 15:27 UTC, Kevan-Y commented on docs/E-Secondary-Storage/text-files.md
>  ---
Add a description here, check the standard https://github.com/Seneca-ICTOER/IPC144/pull/143

2021-12-09 14:27 UTC, humphd commented
This is failing CI (yeah @mqnguyen5!):

```
 Unable to build website for locale "en".
Error: Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /E-Secondary-Storage/text-files:
   -> linking to ../introduction/information (resolved as: /introduction/information)
   -> linking to ../modularity/pointers (resolved as: /modularity/pointers)
   -> linking to ../data-structures/structures (resolved as: /data-structures/structures)
```

2021-12-09 15:01 UTC, humphd commented
@CameronGray1210 this is a good example of how our new CI stuff works, in this case, catching a broken link introduced in a PR: https://github.com/Seneca-ICTOER/IPC144/runs/4459967013?check_suite_focus=true.

2021-12-09 16:26 UTC, joshuali7536 commented
Links have been modified to the correct links.

2021-12-10 21:40 UTC, Kevan-Y commented
Could you rebase this branch to the latest main commit?

2021-12-12 22:05 UTC, CameronGray1210 approved these changes
Good job - thanks!

2021-12-12 22:05 UTC, merged