Audit & fix `algorithms.md` page
Seneca-ICTOER/IPC144 pull request #72
Opened 2021-11-12 00:04 UTC by oliver-pham

Fix #28 

- Fix Frontmatter for page to include `id`, `title`, `slug`, and `description`
- Replace `**...**` used as a fourth heading level with `####`
- Fix all code to be wrapped with backticks
- Replace blockquote with Admonitions for clarity
- Include inter-site links to relevant pages
- Fix typo

2021-11-12 20:16 UTC, minhhang107 requested changes
- Line 25 should use `find`
```
Search algorithms finds the index of ...
```
- In `find()` (line 42) and `main()` (line 57): consider removing extra indentation to maintain consistency
```c
int find(int skuData[], int skuCount, int findSKU)
{
        int i, skuIndex = -1;
        for (i = 0; skuIndex < 0 && i < skuCount; i++)
        ...
        return skuIndex;
}
```

2021-11-14 20:09 UTC, lyu4321 commented on docs/F-Refinements/algorithms.md
> +Consider the following program, which calculates the total purchase price for a set of products.  The user enters the SKU (Stock-Keeping Unit) for each product purchased and the quantity.  Some produ
```suggestion
Consider the following program, which calculates the total purchase price for a set of products.  The user enters the SKU (Stock-Keeping Unit) for each product purchased and the quantity.  Some products attract HST (Harmonized Sales Tax), while others do not.  We store the SKUs, unit prices and tax status in three parallel arrays.  The tax status array is the masking array.  The user enters 0 to terminate input.
```

2021-11-14 20:10 UTC, lyu4321 commented on docs/F-Refinements/algorithms.md
> +Consider the following program, which calculates the total purchase price for a set of products.  The user enters the SKU (Stock-Keeping Unit) for each product purchased and the quantity.  Some produ
Also in line 459, `swap` should be `swaps` such as 

```To simulate mixing, the algorithm picks the index of a reference element, randomly picks the index of another element further along in the array and swaps the values stored in the two elements.```

2021-11-14 20:11 UTC, lyu4321 commented
Also in line 459, `swap` should be `swaps` such as:

```To simulate mixing, the algorithm picks the index of a reference element, randomly picks the index of another element further along in the array and swaps the values stored in the two elements.```

2021-11-17 23:39 UTC, merged

2021-11-17 23:39 UTC, CameronGray1210 commented
Thanks - good work!